### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by theS1LV3R** [xpyxel/blueprint#40]
**Is your feature request related to a problem? Please describe.**
Yeet

**Describe the solution you'd like**
Leaning commands

**Describe alternatives you've considered**
No

**Additional context**
https://canary.discord.com/channels/635632859998060554/635657300199211011/790909726220877834

**Comment by xpyxel** [comment]
This will be looked into after Christmas. Thanks for making the issue, lol.

**Comment by xpyxel** [comment]
This was implemented in commit 80a7c5aeef6f9d35f3fffc8c85aa01a60c7b826f
